setxkbmap -option "caps:swapescape"
dunst &
compton &
mpd &
wallpaper.sh &
sxhkd &
nm-applet &
parcellite &
top --align right
xinput.sh
dwmblocks &
xrdb -merge $XDG_CONFIG_HOME/X11/Xresources
exec dwm
