setxkbmap -option ctrl:nocaps
xcape -e 'Control_L=Escape'
[[ -f $HOME/.config/X11/xmodmap ]] && xmodmap $HOME/.config/X11/xmodmap
dunst &
mpd &
cat $HOME/Pictures/.startWal | xargs feh --bg-scale &
nm-applet &
parcellite &
xinput.sh &
dwmblocks &
xrdb -merge $XDG_CONFIG_HOME/X11/Xresources
sxhkd &
exec dwm
