setxkbmap -option "caps:swapescape"
/usr/lib/kdeconnectd &
indicator-kdeconnect &
dunst &
compton &
mpd &
wallpaper.sh &
nm-applet &
parcellite &
xinput.sh &
dwmblocks &
xrdb -merge $XDG_CONFIG_HOME/X11/Xresources
sxhkd &
exec dwm
